package com.example.mxb.manager;

import com.example.mxb.MxbPlugin;
import com.example.mxb.config.CheatType;
import org.bukkit.entity.Player;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;

public class WarnManager {

    private final MxbPlugin plugin;

        public WarnManager(MxbPlugin plugin) {
                this.plugin = plugin;
                    }

                        public int getCount(String uuid, String cheatType) {
                                try (PreparedStatement ps = plugin.getDatabase().getConnection().prepareStatement(
                                                "SELECT count FROM warn_counts WHERE uuid = ? AND cheat_type = ?")) {
                                                            ps.setString(1, uuid);
                                                                        ps.setString(2, cheatType);
                                                                                    try (ResultSet rs = ps.executeQuery()) {
                                                                                                    if (rs.next()) return rs.getInt("count");
                                                                                                                }
                                                                                                                        } catch (SQLException e) {
                                                                                                                                    e.printStackTrace();
                                                                                                                                            }
                                                                                                                                                    return 0;
                                                                                                                                                        }

                                                                                                                                                            public int addWarn(Player target, CheatType type, Player operator, boolean resultedInBan) {
                                                                                                                                                                    String uuid = target.getUniqueId().toString();
                                                                                                                                                                            long now = System.currentTimeMillis();

                                                                                                                                                                                    try (PreparedStatement ps = plugin.getDatabase().getConnection().prepareStatement(
                                                                                                                                                                                                    "INSERT INTO warn_records (uuid, name, ip, cheat_type, cheat_type_name, " +
                                                                                                                                                                                                                    "operator_uuid, operator_name, time, resulted_in_ban) " +
                                                                                                                                                                                                                                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
                                                                                                                                                                                                                                                ps.setString(1, uuid);
                                                                                                                                                                                                                                                            ps.setString(2, target.getName());
                                                                                                                                                                                                                                                                        ps.setString(3, target.getAddress() == null ? null : target.getAddress().getHostString());
                                                                                                                                                                                                                                                                                    ps.setString(4, type.getId());
                                                                                                                                                                                                                                                                                                ps.setString(5, type.getName());
                                                                                                                                                                                                                                                                                                            ps.setString(6, operator == null ? null : operator.getUniqueId().toString());
                                                                                                                                                                                                                                                                                                                        ps.setString(7, operator == null ? "控制台" : operator.getName());
                                                                                                                                                                                                                                                                                                                                    ps.setLong(8, now);
                                                                                                                                                                                                                                                                                                                                                ps.setInt(9, resultedInBan ? 1 : 0);
                                                                                                                                                                                                                                                                                                                                                            ps.executeUpdate();
                                                                                                                                                                                                                                                                                                                                                                    } catch (SQLException e) {
                                                                                                                                                                                                                                                                                                                                                                                plugin.getLogger().log(Level.SEVERE, "写入警告记录失败", e);
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                int newCount = getCount(uuid, type.getId()) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                        try (PreparedStatement ps = plugin.getDatabase().getConnection().prepareStatement(
                                                                                                                                                                                                                                                                                                                                                                                                                        "INSERT INTO warn_counts (uuid, cheat_type, count) VALUES (?, ?, ?) " +
                                                                                                                                                                                                                                                                                                                                                                                                                                        "ON CONFLICT(uuid, cheat_type) DO UPDATE SET count = ?")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ps.setString(1, uuid);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ps.setString(2, type.getId());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ps.setInt(3, newCount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ps.setInt(4, newCount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ps.executeUpdate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (SQLException e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        plugin.getLogger().log(Level.SEVERE, "更新警告计数失败", e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return newCount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public boolean clearCount(String uuid, String cheatType) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try (PreparedStatement ps = plugin.getDatabase().getConnection().prepareStatement(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "DELETE FROM warn_counts WHERE uuid = ? AND cheat_type = ?")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ps.setString(1, uuid);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ps.setString(2, cheatType);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ps.executeUpdate() > 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (SQLException e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e.printStackTrace();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }