package com.example.mxb.util;

import java.text.SimpleDateFormat;
import java.util.Date;

public class TimeUtil {

    /** 解析时长, -1 表示永久 */
        public static long parseDuration(String input) {
                if (input == null) return -1;
                        String s = input.trim().toLowerCase();
                                if (s.equals("-1") || s.equals("permanent") || s.equals("perm")) return -1L;

                                        long total = 0;
                                                int i = 0;
                                                        StringBuilder num = new StringBuilder();
                                                                while (i < s.length()) {
                                                                            char c = s.charAt(i);
                                                                                        if (Character.isDigit(c)) {
                                                                                                        num.append(c);
                                                                                                                        i++;
                                                                                                                                        continue;
                                                                                                                                                    }
                                                                                                                                                                String unit;
                                                                                                                                                                            if (s.startsWith("mo", i)) { unit = "mo"; i += 2; }
                                                                                                                                                                                        else if (s.startsWith("y", i)) { unit = "y"; i++; }
                                                                                                                                                                                                    else if (s.startsWith("w", i)) { unit = "w"; i++; }
                                                                                                                                                                                                                else if (s.startsWith("d", i)) { unit = "d"; i++; }
                                                                                                                                                                                                                            else if (s.startsWith("h", i)) { unit = "h"; i++; }
                                                                                                                                                                                                                                        else if (s.startsWith("m", i)) { unit = "m"; i++; }
                                                                                                                                                                                                                                                    else if (s.startsWith("s", i)) { unit = "s"; i++; }
                                                                                                                                                                                                                                                                else { i++; continue; }

                                                                                                                                                                                                                                                                            if (num.length() == 0) continue;
                                                                                                                                                                                                                                                                                        long n = Long.parseLong(num.toString());
                                                                                                                                                                                                                                                                                                    num.setLength(0);

                                                                                                                                                                                                                                                                                                                switch (unit) {
                                                                                                                                                                                                                                                                                                                                case "s": total += n * 1000L; break;
                                                                                                                                                                                                                                                                                                                                                case "m": total += n * 60_000L; break;
                                                                                                                                                                                                                                                                                                                                                                case "h": total += n * 3_600_000L; break;
                                                                                                                                                                                                                                                                                                                                                                                case "d": total += n * 86_400_000L; break;
                                                                                                                                                                                                                                                                                                                                                                                                case "w": total += n * 7L * 86_400_000L; break;
                                                                                                                                                                                                                                                                                                                                                                                                                case "mo": total += n * 30L * 86_400_000L; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                case "y": total += n * 365L * 86_400_000L; break;
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return total == 0 ? -1 : total;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /** 把毫秒转成 "3天5小时" 这样的文字 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public static String formatDuration(long millis) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (millis < 0) return "永久";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        long seconds = millis / 1000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                long days = seconds / 86400; seconds %= 86400;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        long hours = seconds / 3600; seconds %= 3600;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                long minutes = seconds / 60; seconds %= 60;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        StringBuilder sb = new StringBuilder();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (days > 0) sb.append(days).append("天");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (hours > 0) sb.append(hours).append("小时");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (minutes > 0) sb.append(minutes).append("分");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (sb.length() == 0) sb.append(seconds).append("秒");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return sb.toString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /** 把时间戳变成 "2026-09-11 12:00:00" 这样的格式 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public static String formatDate(long timestamp) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (timestamp < 0) return "永久";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(timestamp));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /** 计算剩余时间（毫秒） */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public static long remaining(long endTime) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (endTime < 0) return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return Math.max(0, endTime - System.currentTimeMillis());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /** 把 & 替换成 Minecraft 的颜色代码 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public static String color(String s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return org.bukkit.ChatColor.translateAlternateColorCodes('&', s);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }